### ISSUE TITLE
内容纠错和疑惑

### ISSUE THREAD

**Issue by Cobasso** [mini-full/zju-welcome#11]
1.生活 -校园区域-体育运动区的9和10在图上标反了
2.入学-入校交通里是不是忘了杭州西站
3.小剧场好像很久没有电影放了（sad

**Comment by mini-full** [comment]
感谢指正，已经更新到github page
小剧场不是23年还放了不少电影吗哈哈哈，有过中国乒乓、宇宙探索编辑部这些的公演
