### ISSUE TITLE
生活-学生组织与社团-文琴艺术团建议

### ISSUE THREAD

**Issue by ShiQi177** [mini-full/zju-welcome#110]
学生组织与社团里有提及文琴艺术团，目前文琴艺术团下属分团共有8个，分别是：文琴民族乐团、文琴交响乐团、文琴电声乐团、文琴管乐团、文琴键盘乐团、文琴舞蹈团、黑白剧社、文琴合唱团。具体信息可以在体艺部官网或公众号内查阅，如果可以的话希望能补充完整，辛苦^^

**Comment by mini-full** [comment]
感谢你的建议，已经在https://github.com/mini-full/zju-welcome/commit/e246b55a5cb56f86eb18a0ee520d614bb910ff25中更新
