### ISSUE TITLE
浙大体艺下载二维码指正

### ISSUE THREAD

**Issue by ZZH6821** [mini-full/zju-welcome#137]
**常用信息-信息平台-软件使用页**中提供的**浙大体艺**下载二维码***已失效***
体艺部官网中目前可用的下载方式如下http://tyys.zju.edu.cn/redir.php?catalog_id=172638

**Comment by mini-full** [comment]
感谢提醒，已经在 https://github.com/mini-full/zju-welcome/commit/c0fe7277a5f8e3b797aca0ad40bf73b96f874374 中更新。
