### ISSUE TITLE
一些关于内容的纠错

### ISSUE THREAD

**Issue by jzl-66666a** [mini-full/zju-welcome#8]
1.建设银行在西区有一支行
2.组织委员志愿活动相关的职能已被独立出来，现新设“青志委员”班委，对接学院青志部和素拓部，负责协助同学解决志愿服务相关（志愿者信息录入，问题解答，小时数补录，志愿活动立项）和社会实践相关（问题解答，社会实践活动立项）问题
3.在选课指导中的某一页提及体育课和体育专项辅导课，后者易和公体部开设的体育辅导课搞混，建议直接使用“身体素质课”
4.“教务系统”专题实际上几乎为选课指导专项，建议补充对教务系统（以及教务网）其他功能的介绍（或者直接改名成选课指导吧）

**Comment by mini-full** [comment]
感谢纠错，已经更新到最近commit中，github page已更新，zjuers页面稍后更新。

青志委员这个加进去了，但我印象中去年还是竺院有云峰没有，不知道是不是有学园之间的差异？

**Comment by jzl-66666a** [comment]
22级蓝田是有的，其他学园不太清楚
本身也是一个存在感不高的班委
